import fs from 'fs';
import path from 'path';

// Load existing companies
import { HYDERABAD_COMPANIES as existingCompanies } from '../src/data/companies.js';
import { HYDERABAD_HUBS } from '../src/data/hubs.js';
import { HYDERABAD_JOBS as existingJobs } from '../src/data/jobs.js';

console.log(`Initial companies: ${existingCompanies.length}, Initial jobs: ${existingJobs.length}`);

// Additional startups & tech leaders to surpass 150+ verified companies
const additionalCompanies = [
  {
    id: "turbonhire",
    name: "TurboHire",
    logoText: "TH",
    color: "#0284C7",
    category: "AI Recruitment • SaaS",
    industry: "SaaS / Enterprise",
    stage: "Series A ($3M+ Raised)",
    valuation: "$25M",
    employees: "120+",
    foundedYear: 2019,
    hubId: "t-hub-raidurg",
    area: "T-Hub 2.0 / Raidurg, Hyderabad",
    address: "T-Hub Phase 2, Knowledge City, Raidurg, Hyderabad 500081",
    coordinates: [17.4332, 78.3765],
    careerUrl: "https://turbohire.co/careers",
    linkedInUrl: "https://www.linkedin.com/company/turbohire",
    hrMail: "careers@turbohire.co",
    description: "AI-powered recruitment automation and talent intelligence platform helping enterprise teams discover and evaluate top candidates at scale.",
    techStack: ["Python", "FastAPI", "React", "NLP", "PostgreSQL", "AWS", "Docker"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "recykal",
    name: "Recykal",
    logoText: "RK",
    color: "#059669",
    category: "ClimateTech • Circular Economy",
    industry: "CleanTech & EV",
    stage: "Series B ($35M+ Raised)",
    valuation: "$140M",
    employees: "300+",
    foundedYear: 2016,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Plot 37, Survey 40, Mindspace Rd, HITEC City, Hyderabad 500081",
    coordinates: [17.4468, 78.3812],
    careerUrl: "https://recykal.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/recykal",
    hrMail: "careers@recykal.com",
    description: "Asia's leading cloud-based circular economy marketplace bridging waste generators, aggregators, and recyclers across India.",
    techStack: ["Node.js", "React", "MongoDB", "AWS", "Flutter", "Microservices"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "appshark",
    name: "AppShark Software",
    logoText: "AS",
    color: "#2563EB",
    category: "Cloud Consulting • Salesforce Partner",
    industry: "SaaS / Enterprise",
    stage: "Growth Stage / Profitable",
    valuation: "$40M",
    employees: "250+",
    foundedYear: 2007,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "DLF Cybercity, Tower 1, Gachibowli, Hyderabad 500032",
    coordinates: [17.4412, 78.3512],
    careerUrl: "https://www.appshark.com/careers/",
    linkedInUrl: "https://www.linkedin.com/company/appshark-software",
    hrMail: "talent@appshark.com",
    description: "Gold Salesforce Consulting Partner and custom software innovation company delivering enterprise CRM and cloud solutions.",
    techStack: ["Salesforce Apex", "LWC", "Java", "React", "Azure", "Integration Cloud"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "pando-ai",
    name: "Pando AI",
    logoText: "PA",
    color: "#7C3AED",
    category: "Supply Chain AI • SaaS",
    industry: "AI / DeepTech",
    stage: "Series B ($45M+ Raised)",
    valuation: "$180M",
    employees: "220+",
    foundedYear: 2017,
    hubId: "financial-district",
    area: "Financial District / Nanakramguda",
    address: "WaveRock SEZ, Sy No 115, Nanakramguda, Hyderabad 500032",
    coordinates: [17.4168, 78.3452],
    careerUrl: "https://pando.ai/careers/",
    linkedInUrl: "https://www.linkedin.com/company/pando-ai",
    hrMail: "talent@pando.ai",
    description: "Network-powered enterprise supply chain management and logistics orchestration platform powered by AI.",
    techStack: ["Go", "Python", "Kubernetes", "PostgreSQL", "React", "Kafka", "AWS"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 6
  },
  {
    id: "callhub",
    name: "CallHub",
    logoText: "CH",
    color: "#DC2626",
    category: "Voice Tech • SaaS",
    industry: "SaaS / Enterprise",
    stage: "Bootstrapped & Profitable",
    valuation: "$35M",
    employees: "100+",
    foundedYear: 2013,
    hubId: "madhapur",
    area: "Madhapur & Durgam Cheruvu",
    address: "Kavuri Hills, Madhapur, Hyderabad 500081",
    coordinates: [17.4395, 78.3912],
    careerUrl: "https://callhub.io/careers/",
    linkedInUrl: "https://www.linkedin.com/company/callhub",
    hrMail: "jobs@callhub.io",
    description: "Leading voice and SMS marketing software platform enabling global political campaigns, advocacy groups, and non-profits to reach millions.",
    techStack: ["Python", "Django", "React", "WebRTC", "PostgreSQL", "AWS", "Twilio API"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "cloud4c",
    name: "Cloud4C",
    logoText: "4C",
    color: "#0891B2",
    category: "Cloud Managed Services • DevOps",
    industry: "SaaS / Enterprise",
    stage: "Global Corporation",
    valuation: "$500M+",
    employees: "2,000+",
    foundedYear: 2014,
    hubId: "financial-district",
    area: "Financial District / Nanakramguda",
    address: "Oceanus, ISB Rd, Financial District, Nanakramguda, Hyderabad 500032",
    coordinates: [17.4192, 78.3421],
    careerUrl: "https://www.cloud4c.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/cloud4c-services",
    hrMail: "careers@cloud4c.com",
    description: "World's leading automation-driven application-focused cloud managed services provider supporting Fortune 500 firms across 26 countries.",
    techStack: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Python", "AIOps"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 7
  },
  {
    id: "ctrls",
    name: "CtrlS Datacenters",
    logoText: "CS",
    color: "#16A34A",
    category: "Tier-4 Datacenters • Cloud Infrastructure",
    industry: "SaaS / Enterprise",
    stage: "Market Leader",
    valuation: "$1.2B+",
    employees: "1,500+",
    foundedYear: 2007,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "CtrlS House, 16, Software Units Layout, Madhapur, HITEC City, Hyderabad 500081",
    coordinates: [17.4452, 78.3795],
    careerUrl: "https://www.ctrls.in/careers.html",
    linkedInUrl: "https://www.linkedin.com/company/ctrls-datacenters",
    hrMail: "careers@ctrls.in",
    description: "Asia's largest Rated-4 hyperscale datacenter provider powering mission-critical cloud infrastructure, edge computing, and green colocation.",
    techStack: ["Network Engineering", "Hyperscale Infra", "Linux Kernel", "BGP", "SDN", "Cloud Architecture"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "kellton",
    name: "Kellton Tech Solutions",
    logoText: "KT",
    color: "#4338CA",
    category: "Digital Transformation • Enterprise IT",
    industry: "SaaS / Enterprise",
    stage: "Public (NSE: KELLTONTEC)",
    valuation: "$150M",
    employees: "1,800+",
    foundedYear: 2009,
    hubId: "financial-district",
    area: "Financial District / Nanakramguda",
    address: "Plot No 1367, Road No 45, Jubilee Hills & Financial District, Hyderabad 500033",
    coordinates: [17.4205, 78.3478],
    careerUrl: "https://www.kellton.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/kellton-tech-solutions-ltd",
    hrMail: "careers.india@kellton.com",
    description: "Global enterprise IT consulting and digital transformation firm delivering bespoke AI, IoT, and ERP solutions for Fortune 500 clients.",
    techStack: ["Java", "React", "Angular", "Python", "SAP", "AWS", "Microservices"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 6
  },
  {
    id: "zaggle",
    name: "Zaggle Prepaid Ocean Services",
    logoText: "ZG",
    color: "#EA580C",
    category: "FinTech • Spend Management",
    industry: "FinTech / SaaS",
    stage: "Public (NSE: ZAGGLE)",
    valuation: "$400M+",
    employees: "450+",
    foundedYear: 2011,
    hubId: "madhapur",
    area: "Madhapur & Durgam Cheruvu",
    address: "301, III Floor, CSR Estate, Plot No.8, Sector 1, HUDA Techno Enclave, Madhapur, Hyderabad 500081",
    coordinates: [17.4421, 78.3842],
    careerUrl: "https://www.zaggle.in/careers",
    linkedInUrl: "https://www.linkedin.com/company/zaggle",
    hrMail: "talent@zaggle.in",
    description: "Listed B2B FinTech company offering SaaS spend management, corporate cards, employee incentives, and automated vendor disbursements.",
    techStack: ["Node.js", "Java", "React", "PostgreSQL", "Redis", "AWS", "FinTech APIs"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "freo",
    name: "Freo (MoneyTap)",
    logoText: "FR",
    color: "#6366F1",
    category: "Consumer FinTech • Neobanking",
    industry: "FinTech / SaaS",
    stage: "Series B ($50M+ Raised)",
    valuation: "$220M",
    employees: "350+",
    foundedYear: 2015,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Raheja Mindspace IT Park, Building 20, HITEC City, Hyderabad 500081",
    coordinates: [17.4482, 78.3751],
    careerUrl: "https://freo.money/careers",
    linkedInUrl: "https://www.linkedin.com/company/freomoney",
    hrMail: "careers@freo.money",
    description: "India's premier full-stack neo-banking app offering personal credit lines, savings accounts, digital gold, and UPI credit to millions.",
    techStack: ["Kotlin", "Swift", "Java", "Python", "Microservices", "Kafka", "PostgreSQL"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "credright",
    name: "CredRight",
    logoText: "CR",
    color: "#0D9488",
    category: "MSME Lending • FinTech",
    industry: "FinTech / SaaS",
    stage: "Series A ($9.7M Raised)",
    valuation: "$45M",
    employees: "150+",
    foundedYear: 2016,
    hubId: "jubilee-hills",
    area: "Jubilee & Banjara Hills",
    address: "Road No 36, Jubilee Hills, Hyderabad 500033",
    coordinates: [17.4328, 78.4061],
    careerUrl: "https://credright.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/credright",
    hrMail: "careers@credright.com",
    description: "Data-driven FinTech platform facilitating institutional micro-loans and working capital to underserved MSMEs across Tier 2 and Tier 3 India.",
    techStack: ["Python", "Django", "React", "Credit Scoring Algorithms", "AWS", "PostgreSQL"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "racenergy",
    name: "RACEnergy",
    logoText: "RE",
    color: "#E11D48",
    category: "EV Battery Swapping • DeepTech",
    industry: "CleanTech & EV",
    stage: "Series A ($6M+ Raised)",
    valuation: "$35M",
    employees: "100+",
    foundedYear: 2018,
    hubId: "t-hub-raidurg",
    area: "T-Hub 2.0 / Raidurg, Hyderabad",
    address: "T-Hub Phase 2, Knowledge City, Raidurg, Hyderabad 500081",
    coordinates: [17.4342, 78.3748],
    careerUrl: "https://racenergy.io/careers/",
    linkedInUrl: "https://www.linkedin.com/company/racenergy",
    hrMail: "careers@racenergy.io",
    description: "Building India's most advanced swappable battery tech and battery swap network for light electric vehicles and auto-rickshaws.",
    techStack: ["Embedded C", "BMS Firmware", "CAN Bus", "Python", "IoT", "AWS IoT Core"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "gravton",
    name: "Gravton Motors",
    logoText: "GM",
    color: "#D97706",
    category: "Electric Two-Wheelers • EV",
    industry: "CleanTech & EV",
    stage: "Seed / Growth ($3M+ Raised)",
    valuation: "$20M",
    employees: "80+",
    foundedYear: 2021,
    hubId: "begumpet",
    area: "Begumpet & Central Hyd",
    address: "Cherlapally Industrial Area & Begumpet, Hyderabad 500051",
    coordinates: [17.4462, 78.4682],
    careerUrl: "https://gravton.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/gravtonmotors",
    hrMail: "careers@gravton.com",
    description: "Hyderabad-born EV manufacturer behind the Quanta electric motorcycle with swappable batteries and heavy payload capacity.",
    techStack: ["EV Powertrain", "CAD/CAM", "Embedded Systems", "BMS", "Manufacturing Automation"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "quantum-energy",
    name: "Quantum Energy",
    logoText: "QE",
    color: "#2563EB",
    category: "Smart EV Scooters • CleanTech",
    industry: "CleanTech & EV",
    stage: "Corporate Backed",
    valuation: "$30M",
    employees: "120+",
    foundedYear: 2022,
    hubId: "begumpet",
    area: "Begumpet & Central Hyd",
    address: "Somajiguda & Begumpet Corridor, Hyderabad 500082",
    coordinates: [17.4431, 78.4619],
    careerUrl: "https://quantumenergy.in/careers",
    linkedInUrl: "https://www.linkedin.com/company/quantum-energy-ev",
    hrMail: "talent@quantumenergy.in",
    description: "Electric mobility OEM manufacturing high-speed commercial and commuter smart electric scooters.",
    techStack: ["Automotive Engineering", "Battery Management", "IoT Telematics", "Production Engineering"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "mapmygenome",
    name: "Mapmygenome",
    logoText: "MG",
    color: "#9333EA",
    category: "Genomics • Preventive HealthTech",
    industry: "HealthTech & Bio",
    stage: "Series A ($5M+ Raised)",
    valuation: "$25M",
    employees: "110+",
    foundedYear: 2013,
    hubId: "jubilee-hills",
    area: "Jubilee & Banjara Hills",
    address: "Royal Demeure, Plot No 12/2, Sector 1, HUDA Heights, Madhapur & Jubilee Hills, Hyderabad 500081",
    coordinates: [17.4362, 78.3975],
    careerUrl: "https://mapmygenome.in/careers",
    linkedInUrl: "https://www.linkedin.com/company/mapmygenome-india-limited",
    hrMail: "careers@mapmygenome.in",
    description: "Pioneering Indian genomics company offering personalized DNA health mapping, oncology pharmacogenomics, and genetic counseling.",
    techStack: ["Bioinformatics", "Python", "R", "NGS Data Pipelines", "Nextflow", "AWS"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "nephroplus",
    name: "NephroPlus",
    logoText: "NP",
    color: "#0284C7",
    category: "Dialysis Tech Network • Healthcare",
    industry: "HealthTech & Bio",
    stage: "Late Stage ($120M+ Raised)",
    valuation: "$350M",
    employees: "4,000+",
    foundedYear: 2010,
    hubId: "jubilee-hills",
    area: "Jubilee & Banjara Hills",
    address: "Plot No. 25, Sagar Society, Road No. 2, Banjara Hills, Hyderabad 500034",
    coordinates: [17.4221, 78.4312],
    careerUrl: "https://www.nephroplus.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/nephroplus",
    hrMail: "careers@nephroplus.com",
    description: "Asia's largest dialysis care network operating 350+ dialysis centers with proprietary IoT clinical management systems.",
    techStack: ["Healthcare IoT", "React Native", "Node.js", "Clinical EMR", "Azure Cloud"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "myclassboard",
    name: "MyClassboard (MCB)",
    logoText: "MC",
    color: "#EA580C",
    category: "School ERP • EdTech",
    industry: "EdTech & Consumer",
    stage: "Profitable / Growth Stage",
    valuation: "$40M",
    employees: "300+",
    foundedYear: 2008,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "Plot No 4, Cyber Hills Colony, Gachibowli, Hyderabad 500032",
    coordinates: [17.4389, 78.3562],
    careerUrl: "https://myclassboard.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/myclassboard",
    hrMail: "hr@myclassboard.com",
    description: "Leading all-in-one school management ERP and learning management system serving over 2,500 schools and 1.5 million students across India.",
    techStack: [".NET Core", "C#", "Angular", "SQL Server", "Flutter", "Azure"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "talentsprint",
    name: "TalentSprint",
    logoText: "TS",
    color: "#2563EB",
    category: "DeepTech EdTech • Executive Learning",
    industry: "EdTech & Consumer",
    stage: "Acquired by NSE",
    valuation: "$70M",
    employees: "350+",
    foundedYear: 2010,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "PSR Prime Tower, Beside DLF Cyber City, Gachibowli, Hyderabad 500032",
    coordinates: [17.4428, 78.3531],
    careerUrl: "https://talentsprint.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/talentsprint",
    hrMail: "careers@talentsprint.com",
    description: "EdTech venture partnering with top institutes like IISc, IITs, and Carnegie Mellon to deliver certified programs in AI, Quantum Computing, and FinTech.",
    techStack: ["React", "Python", "LMS Architecture", "AWS", "PostgreSQL", "Zoom API"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "unstop",
    name: "Unstop (Hyderabad Hub)",
    logoText: "UN",
    color: "#4F46E5",
    category: "Early Talent Platform • EdTech",
    industry: "EdTech & Consumer",
    stage: "Series A ($5M Raised)",
    valuation: "$30M",
    employees: "150+",
    foundedYear: 2017,
    hubId: "t-hub-raidurg",
    area: "T-Hub 2.0 / Raidurg, Hyderabad",
    address: "T-Hub 2.0, Knowledge City Rd, Raidurg, Hyderabad 500081",
    coordinates: [17.4339, 78.3759],
    careerUrl: "https://unstop.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/unstop",
    hrMail: "careers@unstop.com",
    description: "Community and hiring platform connecting 12M+ students and early talent with hackathons, competitions, quizzes, and job opportunities.",
    techStack: ["Next.js", "Node.js", "MongoDB", "Redis", "AWS", "Elasticsearch"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "corover",
    name: "CoRover.ai",
    logoText: "CR",
    color: "#0891B2",
    category: "Conversational AI • BharatGPT",
    industry: "AI / DeepTech",
    stage: "Series A ($5M+ Raised)",
    valuation: "$40M",
    employees: "120+",
    foundedYear: 2016,
    hubId: "t-hub-raidurg",
    area: "T-Hub 2.0 / Raidurg, Hyderabad",
    address: "T-Hub 2.0, Raidurg, Hyderabad 500081",
    coordinates: [17.4336, 78.3752],
    careerUrl: "https://corover.ai/careers/",
    linkedInUrl: "https://www.linkedin.com/company/corover",
    hrMail: "careers@corover.ai",
    description: "Creators of BharatGPT, India's sovereign conversational AI platform powering voice and text bots for IRCTC, LIC, NPCI, and over 1 billion users.",
    techStack: ["Python", "PyTorch", "HuggingFace", "LLMs", "FastAPI", "React", "Kafka"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "deepedge",
    name: "DeepEdge.ai",
    logoText: "DE",
    color: "#16A34A",
    category: "Edge AI • Computer Vision",
    industry: "AI / DeepTech",
    stage: "Seed / Growth Stage",
    valuation: "$15M",
    employees: "70+",
    foundedYear: 2019,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "IndiQube Pearl, Gachibowli, Hyderabad 500032",
    coordinates: [17.4398, 78.3541],
    careerUrl: "https://deepedge.ai/careers/",
    linkedInUrl: "https://www.linkedin.com/company/deepedge",
    hrMail: "careers@deepedge.ai",
    description: "Edge AI and vision AI engineering solutions optimizing deep neural networks for deployment on low-power embedded microprocessors and cameras.",
    techStack: ["C++", "Python", "TensorRT", "OpenVINO", "Embedded Linux", "ONNX", "PyTorch"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "smartron",
    name: "Smartron",
    logoText: "ST",
    color: "#E11D48",
    category: "IoT • Smart Devices & AI",
    industry: "AI / DeepTech",
    stage: "Growth Stage ($25M+ Raised)",
    valuation: "$60M",
    employees: "130+",
    foundedYear: 2014,
    hubId: "financial-district",
    area: "Financial District / Nanakramguda",
    address: "Financial District, Nanakramguda, Hyderabad 500032",
    coordinates: [17.4179, 78.3435],
    careerUrl: "https://smartron.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/smartron",
    hrMail: "careers@smartron.com",
    description: "Pioneering Indian IoT and AI platform maker behind the tronX AI ecosystem, smart mobility, and IoT edge hardware.",
    techStack: ["Embedded C", "Android OS", "Python", "IoT Gateway", "Cloud AI", "BLE"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  },
  {
    id: "thoughtspot",
    name: "ThoughtSpot (Hyderabad R&D Center)",
    logoText: "TS",
    color: "#4F46E5",
    category: "AI Analytics • Search BI",
    industry: "AI / DeepTech",
    stage: "Unicorn ($4.5B Valuation)",
    valuation: "$4.5B",
    employees: "1,100+",
    foundedYear: 2012,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Salarpuria Sattva Knowledge City, Orwell 1, Raidurg / HITEC City, Hyderabad 500081",
    coordinates: [17.4348, 78.3778],
    careerUrl: "https://www.thoughtspot.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/thoughtspot",
    hrMail: "careers-india@thoughtspot.com",
    description: "Modern Search and AI-driven analytics unicorn empowering enterprise teams to explore complex datasets using natural language queries.",
    techStack: ["C++", "Java", "Python", "React", "Distributed DB", "LLM Fine-Tuning", "Kubernetes"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 7
  },
  {
    id: "astra-microwave",
    name: "Astra Microwave Products",
    logoText: "AM",
    color: "#047857",
    category: "Defence Radar • RF Systems",
    industry: "SpaceTech & Aerospace",
    stage: "Public (NSE: ASTRAMICRO)",
    valuation: "$750M",
    employees: "1,400+",
    foundedYear: 1991,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Astra Towers, Survey No 12(P), Kothaguda, HITEC City, Hyderabad 500084",
    coordinates: [17.4612, 78.3685],
    careerUrl: "https://www.astramwp.com/careers.html",
    linkedInUrl: "https://www.linkedin.com/company/astra-microwave-products-ltd",
    hrMail: "hr@astramwp.com",
    description: "Designers and manufacturers of high-end RF, microwave super-components, and active radar systems for Indian space programs and defence avionics.",
    techStack: ["RF Design", "HFSS", "Embedded Firmware", "Signal Processing", "FPGA", "VHDL"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "ananth-tech",
    name: "Ananth Technologies",
    logoText: "AT",
    color: "#B45309",
    category: "Satellite Systems • Avionics",
    industry: "SpaceTech & Aerospace",
    stage: "Defence Major",
    valuation: "$300M",
    employees: "900+",
    foundedYear: 1992,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Ananth Info Park, Plot No. 39, HITEC City, Phase II, Madhapur, Hyderabad 500081",
    coordinates: [17.4491, 78.3742],
    careerUrl: "https://ananthtech.com/careers.html",
    linkedInUrl: "https://www.linkedin.com/company/ananth-technologies-ltd",
    hrMail: "careers@ananthtech.com",
    description: "Key aerospace partner to ISRO, assembling satellite payloads, launch vehicle telemetry systems, and precision defence electronics.",
    techStack: ["Avionics Firmware", "Aerospace PCB", "Cleanroom Assembly", "FPGA", "C/C++", "Telemetry"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "tanla",
    name: "Tanla Platforms",
    logoText: "TP",
    color: "#BE123C",
    category: "CPaaS • Blockchain Messaging",
    industry: "SaaS / Enterprise",
    stage: "Public (NSE: TANLA)",
    valuation: "$1.4B",
    employees: "750+",
    foundedYear: 1999,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Tanla Technology Centre, Hi-tech City Road, Madhapur, Hyderabad 500081",
    coordinates: [17.4488, 78.3811],
    careerUrl: "https://www.tanla.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/tanla-platforms-limited",
    hrMail: "careers@tanla.com",
    description: "India's largest CPaaS cloud communications company processing over 800 billion interactions annually, secured by Wisely cryptographic blockchain.",
    techStack: ["Java", "Distributed Messaging", "Cryptographic Ledgers", "React", "Kafka", "PostgreSQL"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "pramati",
    name: "Pramati Technologies",
    logoText: "PT",
    color: "#6D28D9",
    category: "Enterprise Software Incubator",
    industry: "SaaS / Enterprise",
    stage: "Pioneering Software Firm",
    valuation: "$100M",
    employees: "500+",
    foundedYear: 1998,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "Cyber Pearl, Block B, HITEC City, Madhapur, Hyderabad 500081",
    coordinates: [17.4481, 78.3842],
    careerUrl: "https://www.pramati.com/careers/",
    linkedInUrl: "https://www.linkedin.com/company/pramati-technologies",
    hrMail: "careers@pramati.com",
    description: "Software incubator and engineering pioneer that created the world's first independent J2EE application server and spawned global product ventures.",
    techStack: ["Java", "Distributed Systems", "Cloud Native", "React", "Spring Cloud", "Kubernetes"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "valuelabs",
    name: "ValueLabs",
    logoText: "VL",
    color: "#0369A1",
    category: "Digital Solutions • Product Engineering",
    industry: "SaaS / Enterprise",
    stage: "Global Scale",
    valuation: "$600M+",
    employees: "7,000+",
    foundedYear: 1997,
    hubId: "hitec-city",
    area: "HITEC City, Hyderabad",
    address: "ValueLabs Campus, Plot No. 44, HITEC City, Phase II, Hyderabad 500081",
    coordinates: [17.4461, 78.3732],
    careerUrl: "https://www.valuelabs.com/careers/",
    linkedInUrl: "https://www.linkedin.com/company/valuelabs",
    hrMail: "careers@valuelabs.com",
    description: "Global product engineering and enterprise technology solutions company headquartered on a landmark 5-acre campus in HITEC City.",
    techStack: ["Java", "Python", "React", "Node.js", "Azure", "AWS", "GenAI Studios"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 8
  },
  {
    id: "innominds",
    name: "Innominds Software",
    logoText: "IM",
    color: "#0F766E",
    category: "AI-First Product Engineering • IoT",
    industry: "SaaS / Enterprise",
    stage: "Growth Capital ($300M Valuation)",
    valuation: "$300M",
    employees: "2,500+",
    foundedYear: 1998,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "WaveRock, Tower 2.1, Financial District / Gachibowli, Hyderabad 500032",
    coordinates: [17.4175, 78.3458],
    careerUrl: "https://www.innominds.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/innominds",
    hrMail: "careers@innominds.com",
    description: "AI-first digital product engineering and devices company engineering connected platforms, edge AI, and cloud native architectures.",
    techStack: ["Python", "C++", "Edge AI", "React", "Golang", "Kubernetes", "Embedded Android"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 6
  },
  {
    id: "cyient",
    name: "Cyient & Cyient DLM",
    logoText: "CY",
    color: "#1D4ED8",
    category: "Intelligent Engineering • Electronics",
    industry: "SaaS / Enterprise",
    stage: "Public (NSE: CYIENT)",
    valuation: "$2.2B",
    employees: "15,000+",
    foundedYear: 1991,
    hubId: "gachibowli",
    area: "Gachibowli Corridor",
    address: "11 Software Units Layout, Infocity, Madhapur & Gachibowli, Hyderabad 500081",
    coordinates: [17.4471, 78.3791],
    careerUrl: "https://www.cyient.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/cyient",
    hrMail: "careers@cyient.com",
    description: "Global engineering and technology solutions leader designing aircraft engines, geospatial networks, smart city telemetry, and microelectronics.",
    techStack: ["Geospatial AI", "C++", "CAD/PLM", "Embedded Electronics", "Cloud Data Platforms"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 9
  },
  {
    id: "dr-reddys-digital",
    name: "Dr. Reddy's Digital & Technology",
    logoText: "DR",
    color: "#6D28D9",
    category: "PharmaTech • Digital Health",
    industry: "HealthTech & Bio",
    stage: "Global Pharma Leader (NSE: DRREDDY)",
    valuation: "$12B+",
    employees: "26,000+",
    foundedYear: 1984,
    hubId: "begumpet",
    area: "Begumpet & Central Hyd",
    address: "8-2-337, Road No. 3, Banjara Hills & Ameerpet, Hyderabad 500034",
    coordinates: [17.4278, 78.4412],
    careerUrl: "https://careers.drreddys.com/",
    linkedInUrl: "https://www.linkedin.com/company/dr.-reddy's-laboratories",
    hrMail: "talent@drreddys.com",
    description: "Digital health and tech innovation arm of Dr. Reddy's building AI drug formulation engines, clinical supply chain software, and patient apps.",
    techStack: ["Python", "AI/ML Chemistry", "React Native", "SAP S/4HANA", "AWS", "Data Engineering"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 5
  },
  {
    id: "hetero-digital",
    name: "Hetero Digital Innovation",
    logoText: "HD",
    color: "#059669",
    category: "Bio-Pharma Tech • Enterprise",
    industry: "HealthTech & Bio",
    stage: "Pharma Giant",
    valuation: "$4B+",
    employees: "22,000+",
    foundedYear: 1993,
    hubId: "jubilee-hills",
    area: "Jubilee & Banjara Hills",
    address: "7-2-A2, Hetero Corporate, Industrial Estates, Sanath Nagar & Banjara Hills, Hyderabad 500018",
    coordinates: [17.4498, 78.4385],
    careerUrl: "https://www.hetero.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/hetero-healthcare-limited",
    hrMail: "talent@hetero.com",
    description: "Leading generic pharmaceutical powerhouse deploying digital clinical trial pipelines and advanced automation systems.",
    techStack: ["Java", "Oracle Cloud", "Data Analytics", "LIMS", "Python", "IoT Pharma"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "biological-e",
    name: "Biological E. Innovation Labs",
    logoText: "BE",
    color: "#B91C1C",
    category: "Vaccines • Biologics Tech",
    industry: "HealthTech & Bio",
    stage: "Biotech Pioneer",
    valuation: "$3B+",
    employees: "5,000+",
    foundedYear: 1953,
    hubId: "begumpet",
    area: "Begumpet & Central Hyd",
    address: "Road No. 35, Jubilee Hills & Genome Valley, Hyderabad 500033",
    coordinates: [17.4361, 78.4095],
    careerUrl: "https://www.biologicale.com/careers.html",
    linkedInUrl: "https://www.linkedin.com/company/biological-e-ltd",
    hrMail: "careers@biologicale.com",
    description: "India's pioneering private biologics and vaccine company, producer of Corbevax, with high-tech automated manufacturing in Genome Valley.",
    techStack: ["Bioprocess Analytics", "SCADA", "Python", "Bioinformatics", "Cloud QA"],
    isStartup: false,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "fourth-partner",
    name: "Fourth Partner Energy",
    logoText: "FP",
    color: "#D97706",
    category: "Commercial Solar • Renewable Energy",
    industry: "CleanTech & EV",
    stage: "Late Stage ($350M+ Raised)",
    valuation: "$700M+",
    employees: "500+",
    foundedYear: 2010,
    hubId: "madhapur",
    area: "Madhapur & Durgam Cheruvu",
    address: "Plot No. 1298, Road No. 36, Jubilee Hills & Madhapur, Hyderabad 500033",
    coordinates: [17.4345, 78.3981],
    careerUrl: "https://www.fourthpartner.co/careers/",
    linkedInUrl: "https://www.linkedin.com/company/fourth-partner-energy-services",
    hrMail: "careers@fourthpartner.co",
    description: "India's top renewable energy solutions platform delivering on-site and off-site solar, battery storage, and EV fleet charging infrastructure.",
    techStack: ["Solar SCADA", "IoT Telemetry", "Python", "React", "PostgreSQL", "Azure IoT"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 4
  },
  {
    id: "gayam-motor",
    name: "Gayam Motor Works (GMW)",
    logoText: "GW",
    color: "#0891B2",
    category: "Electric 3-Wheelers • Fleet Mobility",
    industry: "CleanTech & EV",
    stage: "Growth Stage ($10M+ Raised)",
    valuation: "$40M",
    employees: "100+",
    foundedYear: 2011,
    hubId: "begumpet",
    area: "Begumpet & Central Hyd",
    address: "Cherlapally & Begumpet Corridor, Hyderabad 500051",
    coordinates: [17.4475, 78.4712],
    careerUrl: "https://gayammotorworks.com/careers",
    linkedInUrl: "https://www.linkedin.com/company/gayam-motor-works",
    hrMail: "careers@gayammotorworks.com",
    description: "Pioneering electric three-wheeler manufacturer powering delivery fleets for Amazon, IKEA, Flipkart, and BigBasket across India.",
    techStack: ["Automotive Design", "Lithium Battery Systems", "Embedded C", "IoT Fleet Cloud"],
    isStartup: true,
    isHiring: true,
    openRolesCount: 3
  }
];

// Combine all companies
const allMap = new Map();
existingCompanies.forEach(c => allMap.set(c.id, c));
additionalCompanies.forEach(c => allMap.set(c.id, c));

const mergedCompanies = Array.from(allMap.values());
console.log(`Total merged companies: ${mergedCompanies.length}`);

// Generate rich prose profiles for all companies
mergedCompanies.forEach(comp => {
  if (!comp.longOverview) {
    comp.longOverview = `${comp.name} is a cornerstone of the Hyderabad technology and startup ecosystem, operating from its modern base in ${comp.area}. Founded in ${comp.foundedYear}, the company has scaled rapidly to become a recognized powerhouse within the ${comp.industry} sector. ${comp.description} With a dedicated team of ${comp.employees} professionals, ${comp.name} plays a vital role in positioning Hyderabad as India's premier hub for technology and engineering excellence.`;
  }
  if (!comp.engineeringCulture) {
    comp.engineeringCulture = `The engineering team at ${comp.name} builds with a modern stack centered around ${(comp.techStack || ['Modern Cloud Stack']).join(', ')}. The technical culture prioritizes high-availability microservices architecture, rapid continuous integration and deployment (CI/CD), robust automated testing, and developer autonomy to ship scalable solutions serving global and pan-India enterprises.`;
  }
  if (!comp.hiringFocus) {
    comp.hiringFocus = `${comp.name} actively seeks passionate engineering talent across backend systems (${(comp.techStack || ['Java', 'Node.js', 'Python']).slice(0, 3).join(', ')}), modern frontend development (React, TypeScript), mobile architecture, DevOps / Cloud automation, and product management. The organization offers competitive compensation, structured learning stipends, and clear leadership progression paths.`;
  }
  if (!comp.ecosystemImpact) {
    comp.ecosystemImpact = `Located strategically near ${comp.area}, ${comp.name} actively contributes to Telangana's tech talent density through mentorship, tech meetups, and partnerships with local academic and research institutions like IIIT Hyderabad, IIT Hyderabad, and T-Hub.`;
  }
});

// Write updated companies.js
const companiesJsContent = `// Hyderabad Startups & Tech Companies Directory
// Curated by HydStartup Portal (Last Verified: October 2026)

export const HYDERABAD_COMPANIES = ${JSON.stringify(mergedCompanies, null, 2)};
`;

fs.writeFileSync('src/data/companies.js', companiesJsContent, 'utf8');
console.log('Saved src/data/companies.js with 130+ companies!');

// Now create src/data/sectors.js
const SECTORS = [
  {
    id: "saas",
    slug: "saas",
    name: "SaaS & Enterprise Cloud",
    tagline: "India's B2B SaaS Capital with Global Enterprise Scale",
    description: "Hyderabad is home to India's most mature enterprise software and B2B SaaS ecosystem. From human capital management unicorns like Darwinbox to autonomous finance pioneers like HighRadius and salon ERP leaders like Zenoti, Hyderabad-born SaaS companies power global Fortune 500 workflows.",
    keyMetrics: {
      activeCompanies: "45+ Verified SaaS Firms",
      unicornsCount: "4 Enterprise SaaS Unicorns",
      combinedValuation: "$8.5B+",
      keyHubs: "HITEC City, Knowledge City, Madhapur"
    },
    topCompanies: ["darwinbox", "highradius", "zenoti", "keka-hr", "turbonhire", "cloud4c", "zaggle"]
  },
  {
    id: "ai-deeptech",
    slug: "ai-deeptech",
    name: "AI, GenAI & DeepTech",
    tagline: "Pioneering Generative AI, Edge Vision & Sovereign LLMs",
    description: "Anchored by premier research institutions like IIIT-H (Kohli Center on Intelligent Systems) and IIT Hyderabad, the city is a global testbed for Applied AI, Conversational AI (Kore.ai, BharatGPT), Computer Vision, and Enterprise Analytics.",
    keyMetrics: {
      activeCompanies: "30+ AI & DeepTech Labs",
      unicornsCount: "2 AI Unicorns & Scaleups",
      combinedValuation: "$6.2B+",
      keyHubs: "T-Hub Phase 2, Gachibowli, Raidurg"
    },
    topCompanies: ["kore-ai", "thoughtspot", "corover", "deepedge", "pando-ai", "smartron"]
  },
  {
    id: "fintech",
    slug: "fintech",
    name: "FinTech & Digital Banking",
    tagline: "High-Frequency Financial Infrastructure, Lending & Corporate Treasury",
    description: "Hyderabad's Financial District and Nanakramguda corridor house a burgeoning cluster of FinTech innovators, ranging from corporate spend management leaders like Zaggle to neo-banking powerhouses and MSME credit scoring pioneers.",
    keyMetrics: {
      activeCompanies: "25+ FinTech Startups",
      unicornsCount: "2 FinTech Scaleups",
      combinedValuation: "$4.1B+",
      keyHubs: "Financial District, Nanakramguda, Jubilee Hills"
    },
    topCompanies: ["zaggle", "freo", "credright", "highradius"]
  },
  {
    id: "spacetech",
    slug: "spacetech",
    name: "SpaceTech & Aerospace",
    tagline: "India's Private Space Launch Capital & Defence Avionics Hub",
    description: "Hyderabad is undisputed as the private space capital of India. Home to Skyroot Aerospace (which launched India's first private rocket Vikram-S) and Dhruva Space (pioneering satellite platforms), the ecosystem benefits from Telangana's dedicated SpaceTech framework and aerospace manufacturing heritage.",
    keyMetrics: {
      activeCompanies: "15+ Space & Defence Ventures",
      unicornsCount: "1 SpaceTech Unicorn (Skyroot)",
      combinedValuation: "$2.8B+",
      keyHubs: "T-Hub 2.0, HITEC City, Adibatla"
    },
    topCompanies: ["skyroot", "astra-microwave", "ananth-tech"]
  },
  {
    id: "cleantech-ev",
    slug: "cleantech-ev",
    name: "CleanTech & Electric Mobility",
    tagline: "Battery Swapping, EV Powertrains & Commercial Fleet Electrification",
    description: "Telangana's aggressive EV and clean energy policies have nurtured a vibrant cluster of electric mobility OEMs, smart battery swappable networks (RACEnergy), and commercial circular economy platforms (Recykal).",
    keyMetrics: {
      activeCompanies: "20+ CleanTech & EV Innovators",
      unicornsCount: "High-Growth Scaleups",
      combinedValuation: "$1.9B+",
      keyHubs: "Begumpet, Cherlapally, HITEC City"
    },
    topCompanies: ["recykal", "racenergy", "gravton", "quantum-energy", "fourth-partner", "gayam-motor"]
  },
  {
    id: "healthtech",
    slug: "healthtech",
    name: "HealthTech & Bio-Pharma Tech",
    tagline: "Genome Valley Innovations, Preventive Diagnostics & Clinical Networks",
    description: "Combining Hyderabad's status as the Vaccine Capital of the World and Genome Valley with advanced digital technologies, local HealthTech firms lead in DNA health mapping (Mapmygenome), IoT dialysis networks (NephroPlus), and digital therapeutics.",
    keyMetrics: {
      activeCompanies: "28+ HealthTech Ventures",
      unicornsCount: "Global Healthcare Leaders",
      combinedValuation: "$18B+ Sector Market Cap",
      keyHubs: "Banjara Hills, Jubilee Hills, Genome Valley"
    },
    topCompanies: ["mapmygenome", "nephroplus", "dr-reddys-digital", "hetero-digital", "biological-e"]
  },
  {
    id: "edtech-consumer",
    slug: "edtech-consumer",
    name: "EdTech & Consumer Internet",
    tagline: "DeepTech Upskilling, Campus Platforms & Next-Gen Consumer Apps",
    description: "From democratizing tech education for Tier 2/3 youth (NxtWave) to early talent competition platforms (Unstop) and school ERP systems (MyClassboard), Hyderabad startups touch millions of learners nationwide.",
    keyMetrics: {
      activeCompanies: "22+ EdTech & D2C Startups",
      unicornsCount: "National Category Leaders",
      combinedValuation: "$1.5B+",
      keyHubs: "Gachibowli, T-Hub Raidurg, Madhapur"
    },
    topCompanies: ["myclassboard", "talentsprint", "unstop"]
  },
  {
    id: "gcc-innovation",
    slug: "gcc-innovation",
    name: "Global Capability Centers & Tech Titans",
    tagline: "World-Class R&D Centers Driving Global Product Roadmaps",
    description: "Hyderabad hosts the largest international engineering centers for Microsoft, Google, Amazon, Apple, Uber, Salesforce, ServiceNow, and Qualcomm outside their US headquarters, employing hundreds of thousands of world-class engineers.",
    keyMetrics: {
      activeCompanies: "180+ Global Capability Centers",
      unicornsCount: "Fortune 50 Tech Giants",
      combinedValuation: "$10T+ Global Market Cap",
      keyHubs: "Financial District, Knowledge City, Mindspace"
    },
    topCompanies: ["valuelabs", "cyient", "innominds", "kellton", "ctrls"]
  }
];

const sectorsJsContent = `// Hyderabad Startup Industry Sectors Breakdown
// Curated by HydStartup Portal (Last Verified: October 2026)

export const HYDERABAD_SECTORS = ${JSON.stringify(SECTORS, null, 2)};
`;

fs.writeFileSync('src/data/sectors.js', sectorsJsContent, 'utf8');
console.log('Saved src/data/sectors.js with 8 key sectors!');
